### PR TITLE
Jopes words request 

### PR DESCRIPTION
**Pull request by jopes14**
Words added:

Jopes
Jopes's
0ptx
Optx's
stream
tubg
<color=#ff0000><size=40><b>Titan Gamemode
gamemode

### CODE REVIEW

**Comment by ZorroSvardendahl** [comment]
What is tubg?

**Comment by ZorroSvardendahl** [comment]
Because of  #8  we don't allow rich text tags anymore.
Please also remove the rich text tag lines before I merge in.

**Comment by Turdstrider** [comment]
Words requested:
swaws
swag
true
unreal
unity
Turdstrider
Asteroid
Buggs
ball

**Comment by ZorroSvardendahl** [comment]
> Words requested: swaws swag true unreal unity Turdstrider Asteroid Buggs ball

Please create your own pull request., and we won't include a name that includes turd sorry or copyrighted names of services.

**Comment by Turdstrider** [comment]
ok understood

**Pull request merged**
